hipo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts import views as accounts_views
from interactions import views as interactions_views
from recipes import views as recipes_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", recipes_views.RecipeListView.as_view(), name="home"),
    path("share/", recipes_views.ShareView.as_view(), name="share"),
    path(
        "recipes/<int:ingredient_pk>/",
        recipes_views.ListByIngredientView.as_view(),
        name="recipes",
    ),
    path(
        "recipe/<int:recipe_pk>/",
        recipes_views.RecipeDetailView.as_view(),
        name="detail",
    ),
    path("signup/", accounts_views.Signup.as_view(), name="signup"),
    path(
        "login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("like/<int:recipe_pk>/", interactions_views.LikeView.as_view(), name="like"),
    path("rate/<int:recipe_pk>/", interactions_views.RateView.as_view(), name="rate"),
    path("search/", recipes_views.SearchView.as_view(), name="search"),
    path(
        "recipe/<int:recipe_pk>/edit/",
        recipes_views.RecipeUpdateView.as_view(),
        name="edit",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

interactions/models.py
from django.contrib.auth.models import User
from django.db import models

from recipes.models import Recipe


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)


class Rate(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    rate = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=5)

recipes/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Avg


class Recipe(models.Model):
    name = models.CharField(max_length=30)
    image = models.ImageField()
    description = models.TextField(max_length=4000)
    ingredients = models.ManyToManyField("Ingredient")

    created_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    EASY = "0"
    MEDIUM = "1"
    HARD = "2"
    DIFFICULTY_CHOICES = [
        (EASY, "Easy"),
        (MEDIUM, "Medium"),
        (HARD, "Hard"),
    ]
    difficulty = models.CharField(
        max_length=1, choices=DIFFICULTY_CHOICES, default=EASY,
    )

    def __str__(self):
        return self.name

    def get_avg_rate(self):
        avg = self.rate_set.aggregate(Avg("rate"))["rate__avg"]
        return round(avg, 2) if avg is not None else 0


class Ingredient(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name

recipes/forms.py
from django import forms

from .models import Recipe


class RecipeForm(forms.ModelForm):
    description = forms.CharField(
        # NOTE: styling in css probably would be a better practice
        widget=forms.Textarea(attrs={"style": "resize:none;"})
    )

    class Meta:
        model = Recipe
        fields = ["name", "image", "description", "difficulty", "ingredients"]
        help_texts = {
            "ingredients": "Select Ingredients  (Hold down the Ctrl (windows/linux)"
            " / Command (Mac) button to select multiple options.)",
        }

recipes/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.utils import timezone
from django.shortcuts import redirect

from interactions.forms import RateForm
from interactions.models import Like, Rate

from .forms import RecipeForm
from .models import Ingredient, Recipe


class RecipeListView(ListView):
    model = Recipe
    ordering = "-created_at"
    context_object_name = "recipes"
    template_name = "recipes.html"
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["ingredients"] = Ingredient.objects.annotate(
            recipe_count=Count("recipe")
        ).order_by("-recipe_count")[:5]
        return context


@method_decorator(login_required, name="dispatch")
class ShareView(CreateView):
    model = Recipe
    form_class = RecipeForm
    success_url = reverse_lazy("home")
    template_name = "share.html"

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


@method_decorator(login_required, name="dispatch")
class RecipeUpdateView(UpdateView):
    model = Recipe
    form_class = RecipeForm
    template_name = "edit_recipe.html"
    pk_url_kwarg = "recipe_pk"
    context_object_name = "recipe"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(created_by=self.request.user)

    def form_valid(self, form):
        recipe = form.save(commit=False)
        recipe.updated_at = timezone.now()
        recipe.save()
        form.save_m2m()
        return redirect("detail", recipe_pk=recipe.pk)


class RecipeDetailView(DetailView):
    model = Recipe
    context_object_name = "recipe"
    pk_url_kwarg = "recipe_pk"
    template_name = "detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rate_form"] = RateForm
        if self.request.user.is_authenticated:
            context["is_liked"] = Like.objects.filter(
                recipe=context["recipe"], user=self.request.user
            )
            context["is_rated"] = Rate.objects.filter(
                recipe=context["recipe"], user=self.request.user
            )
        else:
            context["is_liked"] = False
            context["is_rated"] = False
        return context


class ListByIngredientView(RecipeListView):
    context_object_name = "recipes"
    template_name = "recipes.html"

    def get_queryset(self):
        return (
            Ingredient.objects.get(pk=self.kwargs["ingredient_pk"])
            .recipe_set.all()
            .order_by("-created_at")
        )


class SearchView(RecipeListView):
    model = Recipe
    context_object_name = "recipes"
    template_name = "recipes.html"

    def get_queryset(self):
        search = self.request.GET.get("search")
        if search:
            # NOTE: description can be useful too
            search = search.replace(",", " ").split()  # parse search string
            query = Q()
            # Search all keywords in both recipe name and recipe ingredients
            for keyword in search:
                query |= Q(name__icontains=keyword)
                query |= Q(ingredients__name__icontains=keyword)
            obj_list = (
                self.model.objects.filter(query).order_by("-created_at").distinct()
            )
        else:
            obj_list = self.model.objects.all().order_by("-created_at")
        return obj_list

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <title>{% block title %}Recipe.com{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
  </head>
  <body>
    {% block body %}
      <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand ml-5" href="{% url "home" %}">Recipe.com</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link ml-5" href="{% url "share" %}">Share a Recipe <span class="sr-only">(current)</span></a>
            </li>
          </ul>
          {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto mr-2">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ user.username }}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                  <a class="dropdown-item" href="{% url "logout" %}">Log out</a>
                </div>
              </li>
            </ul>
          {% else %}
            <form class="form-inline ml-auto mr-2">
              <a href="{% url "login" %}" class="btn btn-outline-secondary">Log in</a>
              <a href="{% url "signup" %}" class="btn btn-primary ml-2">Sign up</a>
            </form>
          {% endif %}
        </div>
      </nav>
      <div class="container-fluid mt-3">
        {% block content %} {% endblock %}
      </div>
    {% endblock body %}
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/detail.html
{% extends 'base.html' %}

{% load static %}

{% load widget_tweaks %}

{% block title %}{{ recipe.name }}{% endblock %}

{% block content %}
  <h2>{{ recipe.name }}</h2>

  <p>
    <img class="mb-1" alt="knife" src="{% static "img/knife.png" %}"/>
    {{ recipe.created_by }}
    <img class="mb-1" alt="muscle" src="{% static "img/muscle.png" %}"/>
    {{ recipe.get_difficulty_display }}
    <img class="mb-1" alt="clock" src="{% static "img/clock.png" %}"/>
    {{ recipe.created_at|date:"j/n/Y" }}
  </p>

  <img class="img-fluid mb-3" alt="{{ recipe.name }}" src="{{ recipe.image.url }}"/>

  <form method="post" action={% url "like" recipe_pk=recipe.pk %} novalidate class="mb-3">
    {% csrf_token %}
    {% if is_liked %}
      <button type="submit" class="btn btn-success">Like ({{ recipe.like_set.count }})</button>
    {% else %}
      <button type="submit" class="btn btn-primary">Like ({{ recipe.like_set.count }})</button>
    {% endif %}
  </form>

  <h4>Ingredients</h4>
  <ul>
    {% for ingredient in recipe.ingredients.all %}
      <li>{{ ingredient.name }}</li>
    {% endfor %}
  </ul>

  <h4>Description</h4>
  <p>{{ recipe.description }}</p>

  <form method="post" action={% url "rate" recipe_pk=recipe.pk %} novalidate class="mb-3">
    {% csrf_token %}
    {% render_field rate_form.rate class="custom-select" style="width:auto"%}
    {% if is_rated %} <!--TODO: display given rate as selected-->
      <button type="submit" class="btn btn-success">Rate</button>
    {% else %}
      <button type="submit" class="btn btn-primary">Rate</button>
    {% endif %}
  </form>

  {% if recipe.created_by == user %}
    <a href="{% url "edit" recipe.pk %}" class="btn btn-primary btn-md mb-3" role="button">Edit</a>
  {% endif %}

{% endblock %}

templates/edit_recipe.html
{% extends 'base.html' %}

{% block title %}Update Recipe{% endblock %}

{% block content %}
  <form method="post" enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">Update</button>
    <a href="{% url "home" %}" class="btn btn-light">Cancel</a>
  </form>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-9">
        {% for recipe in recipes %}
          <div class="card m-4">
            <div class="card-body">
              <h2 class="card-title">{{ recipe.name }}</h2>
              <img class="img-fluid mb-3" alt="{{ recipe.name }}" src="{{ recipe.image.url }}"/>
              <p class="card-text">{{ recipe.description }}</p>
              <p class="mb-0">{{ recipe.created_at }} - by {{ recipe.created_by }}</p>
            </div>
          </div>
        {% endfor %}
      </div>
      <div class="col-3">
        <div class="card m-4">
          <div class="card-body">
            <h3 class="card-title">Search</h3>

          </div>
        </div>
        <div class="card m-4">
          <div class="card-body">
            <h3 class="card-title">Top Used Ingredients</h3>
            <ul>
              {% for ingredient in ingredients %}
                <li>
                  <a href="#">{{ ingredient.name }} ({{ ingredient.recipe_count }})</a>
                </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/login.html
{% extends 'base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
  <div class="row justify-content-center mt-5">
    <div class="col-lg-3 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Log in</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include "includes/form.html" %}
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          Do not have an account? <a href="{% url "signup" %}">Sign up</a>
        </div>
      </div>
      <div class="text-center py-2">
        <small>
          <a href="#" class="text-muted">Forgot your password?</a>
        </small>
      </div>
    </div>
  </div>
{% endblock %}

templates/recipes.html
{% extends 'base.html' %}

{% block content %}
  <div class="container-fluid">
    <div class="row mt-4">
      <div class="col-9">
        {% for recipe in recipes %}
          <div class="card mb-3">
            <div class="card-body">
              <h2 class="card-title">
                <a class="text-dark" href="{% url 'detail' recipe.pk %}">{{ recipe.name }}</a>
              </h2>
              <a href="{% url 'detail' recipe.pk %}">
                <img class="img-fluid mb-3" style="max-height:200px" alt="{{ recipe.name }}" src="{{ recipe.image.url }}"/>
              </a>
              <p class="card-text">{{ recipe.description }}</p>
              <p class="mb-0">{{ recipe.created_at|date:"j/n/Y" }} · {{ recipe.get_avg_rate }}/5 ({{ recipe.rate_set.count }} Votes) ·  {{ recipe.like_set.count }} likes · by {{ recipe.created_by }}
                {% if recipe.created_by == user %}
                  · <a href="{% url "edit" recipe.pk %}" class="btn btn-primary btn-sm" role="button">Edit</a>
                {% endif %}
              </p>
            </div>
          </div>
        {% endfor %}
        {% include 'includes/pagination.html' %}
      </div>
      <div class="col-3">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">Search</h3>
            <form method="get" action={% url "search" %} novalidate>
              <div class="input-group mt-3">
                <input name="search" type="text" class="form-control" placeholder="recipe, ingredient..">
                <div class="input-group-append">
                  <button class="btn btn-primary" type="submit">Search</button>
                </div>
              </div>
            </form>
          </div>
        </div>
        <div class="card mt-3">
          <div class="card-body">
            <h3 class="card-title">Top Used Ingredients</h3>
            <ul>
              {% for ingredient in ingredients %}
                <li>
                  <a href="{% url 'recipes' ingredient.pk %}">{{ ingredient.name }} ({{ ingredient.recipe_count }})</a>
                </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/share.html
{% extends 'base.html' %}

{% block title %}Share a Recipe{% endblock %}

{% block content %}
  <form method="post" enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">Share</button>
    <a href="{% url "home" %}" class="btn btn-light">Cancel</a>
  </form>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
  <div class="row justify-content-center mt-5">
    <div class="col-lg-4 col-md-8 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Sign up</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Create an account</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          Already have an account? <a href="{% url 'login' %}">Log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}